#!/usr/bin/env node
var yargs = require("yargs/yargs");
const {
  getFileNameByString,
  generatorHandler,
  maybeString,
} = require("./common");
const yargsBuilder = yargs(process.argv.slice(2));

let [firstParams, inputName] = yargsBuilder.argv._;
const rootDir = __dirname.replace(/\/scripts/g, "/src");
const fileName = getFileNameByString(inputName) + "-" + firstParams;
const targetFile =
  `${rootDir}/app` +
  (["screen", "slice"].includes(firstParams)
    ? "/features"
    : `/${firstParams}s`);

const exitApp = () => {
  yargsBuilder.showHelp();
  process.exit();
};
/**
 * Generate new file, if it empty or contains special characters then exit functions
 */
const generatorFile = () =>
  !/[a-zA-Z]+/.test(inputName || "")
    ? exitApp()
    : generatorHandler({
        firstParams,
        inputName,
        rootDir,
        targetFile,
        fileName,
      });

yargsBuilder
  .command("component", "Make a component", generatorFile)
  .command("screen", "Make a new screen", generatorFile)
  .command("slice", "Make a new slice", generatorFile)
  .help().argv;

!["component", "screen", "slice", "saga"].includes(firstParams) && exitApp();
