name: lint & typescript check

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./template
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --ignore-scripts
      - name: Copy config file
        run: node ../scripts/github-prepare
      - name: Lint code
        run: yarn github-action-lint
